config/routes.rb
Rails.application.routes.draw do
  # get 'home', to: 'pages#home'
  root to: 'pages#home'
  get 'about', to: 'pages#about', as: :about
  get 'contact', to: 'pages#contact', as: :contact
  get 'restaurants', to: 'restaurants#index', as: :restaurants
  post 'restaurants', to: 'restaurants#create'
  get 'restaurants/:id', to: 'restaurants#show', as: :restaurant
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end

  def home
    @categories = ["japanese", "thai", "jamaican"]
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  RESTAURANTS = {
    1 => { name: "Dishoom", address: "Shoreditch, London", category: "indian" },
    2 => { name: "Sushi Samba", address: "City, London", category: "japanese" }
  }

  def index
    if @category.present?
      @category = params[:food_type]
      @restaurants = RESTAURANTS.select { |id, r| r[:category] == @category }
    else
      @restaurants = RESTAURANTS
    end
  end

  def create
    render plain: "This restaurant would have been created #{params[:name]} #{params[:address]}"
  end

  def show
    @restaurant = RESTAURANTS[params[:id].to_i]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheSpoon306</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>The Spoon App</h1>
    <%= yield %>
    <h4>This is a footer placeholder</h4>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages got created</h1>
<p>Best app in the world</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<ol>
  <% @categories.each do |category| %>
    <li><%= category %></li>
  <% end %>
</ol>

<h1>Find restaurants by category</h1>
<form action="/restaurants" method="get">
  <input type="text" name="food_type" placeholder="What kind of food?">
  <input type="submit">
</form>

<h1>Create new restaurants</h1>
<form action="/restaurants" method="post">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <input type="text" name="name" placeholder="Name">
  <input type="text" name="address" placeholder="Address">
  <input type="submit">
</form>

app/views/restaurants/index.html.erb
<h1>All the restaurants in the app</h1>

<ol>
  <% @restaurants.each do |id, r| %>
    <li>
      <%= link_to r[:name], restaurant_path(id) %>
    </li>
  <% end %>
</ol>


<%#=  %>
<%#  %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant[:name] %></h1>
<h2>Good resto in <%= @restaurant[:address] %></h2>

<%= link_to "Go Home", root_path %>
<%= link_to "See all restaurants", restaurants_path %>